FROM alpine:3.24 AS builder

WORKDIR /src
COPY . .

RUN apk add --no-cache bash git python3
RUN python3 scripts/apply_custom_fallback_patch.py
RUN bash scripts/build.alpine.release.sh

FROM alpine:3.24

RUN apk add --no-cache ca-certificates tzdata

WORKDIR /base
COPY --from=builder /src/subconverter/ /base/

EXPOSE 25500
CMD ["./subconverter"]
